---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/unit
    tag: latest

inputs:
  - name: ci
  - name: git-dutyfree-new

run:
  path: ci/tasks/scripts/test-elm
