---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/unit
    tag: latest

inputs:
  - name: ci
  - name: dutyfree

outputs:
  - name: elmsite

run:
  path: ci/ci/tasks/scripts/elm-build
