apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate

metadata:
  name: {{ .Values.certificate.name }}
  labels:
    {{- include "dutyfree.labels" . | nindent 4 }}
spec:
  domains:
    - {{ .Values.domain }}
