apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dutyfree.fullname" . }}
  labels:
    {{- include "dutyfree.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dutyfree.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dutyfree.selectorLabels" . | nindent 8 }}
      {{- if .Values.annotations }}
      annotations:
{{- toYaml .Values.annotations | nindent 8 -}}
      {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "dutyfree.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.dutyfree.port }}
            - name: PORT
              value: {{ .Values.dutyfree.port | quote }}
            {{- end }}
          ports:
            - name: http
              {{- if .Values.dutyfree.port }}
              containerPort: {{ .Values.dutyfree.port }}
              {{- else }}
              containerPort: 9090
              {{- end }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
