apiVersion: v1
kind: Service
metadata:
  name: {{ include "dutyfree.fullname" . }}
  labels:
    {{- include "dutyfree.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq "LoadBalancer" .Values.service.type) .Values.service.loadBalancerIP -}}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{ end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9090
      protocol: TCP
      # name: http
  selector:
    {{- include "dutyfree.selectorLabels" . | nindent 4 }}
