{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dutyfree.serviceAccountName" . }}
  labels:
{{ include "dutyfree.labels" . | nindent 4 }}
{{- end -}}
