apiVersion: v1
kind: Service
metadata:
  name: {{ include "dutyfree.fullname" . }}
  labels:
    {{- include "dutyfree.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq "LoadBalancer" .Values.service.type) .Values.service.loadBalancerIP -}}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{ end }}
  ports:
    - name: dutyfree-port
      port: {{ .Values.service.port }}
      {{- if .Values.dutyfree.port }}
      targetPort: {{ .Values.dutyfree.port }}
      {{- else }}
      targetPort: 9090
      {{- end }}
      protocol: TCP
  selector:
    {{- include "dutyfree.selectorLabels" . | nindent 4 }}
