#!/bin/bash

curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install

aws cloudformation deploy \
    --template-file cloudformation.yml \
    --tags project=concourse_website \
    --stack-name concourse 

  