resources:
- name: resource-types
  type: git
  icon: playlist-check
  source:
    uri: https://github.com/concourse/resource-types.git
    branch: master

- name: resource-types-website
  type: git
  icon: code-tags
  source:
    uri: git@github.com:concourse/resource-types-website.git
    branch: new-pipeline
    private_key: ((concourse_bot_access_token))
    submodules: all

- name: oci-build-task
  type: registry-image
  icon: calendar-check
  source: {repository: vito/oci-build-task}

- name: resource-types-website-image
  icon: docker
  type: registry-image
  source:
    repository: concourse/dutyfree
    username: ((docker.username))
    password: ((docker.password))

- name: unit-image
  icon: docker
  type: registry-image
  source:
    repository: concourse/unit

- name: helm-image
  icon: docker
  type: registry-image
  source:
    repository: concourse/helm
    username: ((docker.username))
    password: ((docker.password))

jobs:
- name: update-resource-types
  plan:
  - get: resource-types
    trigger: true
  - get: resource-types-website
  - get: unit-image
  - task: update-resource-types
    image: unit-image
    file: resource-types-website/ci/tasks/update-resource-types.yml
  - put: resource-types-website
    image: unit-image
    params: {repository: resource-types-website}

- name: unit-test
  plan:
  - get: resource-types-website
    trigger: true
  - get: unit-image
  - in_parallel:
    - task: elm-tests
      image: unit-image
      file: resource-types-website/ci/tasks/elm-test.yml
    - task: go-tests
      image: unit-image
      file: resource-types-website/ci/tasks/go-test.yml

- name: build-docker
  plan:
  - get: resource-types-website
    passed: [unit-test]
    trigger: true
  - get: oci-build-task
  - in_parallel:
    - task: build-dutyfree
      image: oci-build-task
      privileged: true
      output_mapping: {image: image-df}
      config:
        platform: linux
        params: {CONTEXT: resource-types-website/}
        inputs: [{name: resource-types-website}]
        outputs: [{name: image}]
        caches: [{path: cache-df}]
        run: {path: build}
    - task: build-helm
      image: oci-build-task
      privileged: true
      output_mapping: {image: image-helm}
      config:
        platform: linux
        params:
          DOCKERFILE: resource-types-website/ci/concourse-helm-dockerfile
        inputs: [{name: resource-types-website}]
        outputs: [{name: image}]
        caches: [{path: cache-h}]
        run: {path: build}
  - in_parallel:
    - put: resource-types-website-image
      params: {image: image-df/image.tar}
    - put: helm-image
      params: {image: image-helm/image.tar}

- name: deploy
  plan:
  - get: resource-types-website
    passed: [build-docker]
    trigger: true
  - get: helm-image
    passed: [build-docker]
  - task: helm-deploy
    image: helm-image
    file: resource-types-website/ci/tasks/helm-deploy.yml
    params:
      KUBE_CONFIG: ((kube_config))
