resources:
- name: ci
  type: git
  icon: store-24-hour
  source:
    uri: git@github.com:concourse/dutyfree.git
    branch: pipeline
    paths:
    - ci/
    private_key: ((dutyfreeci.private))

- name: git-dutyfree
  type: git
  icon: store-24-hour
  source:
    uri: git@github.com:concourse/dutyfree.git
    branch: master
    private_key: ((dutyfreeci.private))

- name: git-dutyfree-new
  type: git
  icon: store-24-hour
  source:
    uri: git@github.com:concourse/dutyfree.git
    branch: develop
    private_key: ((dutyfreeci.private))

- name: git-dutyfree-gh-pages
  type: git
  icon: shopping
  source:
    uri: git@github.com:concourse/dutyfree.git
    branch: gh-pages
    private_key: ((dutyfreeci.private))

- name: every-day
  type: time
  source:
    start: 8:00 AM
    stop: 9:00 AM

jobs:
- name: run-tests
  plan:
  - get: ci
  - get: git-dutyfree
    trigger: true
  - task: run-tests
    file: ci/tasks/test.yml

- name: run-elm-tests
  plan:
  - get: ci
  - get: git-dutyfree-new
    trigger: true
  - task: run-elm-tests
    input_mapping: {dutyfree: git-dutyfree-new}
    file: ci/tasks/elm-test.yml

- name: build
  plan:
    - get: ci
    - get: git-dutyfree
      trigger: true
      passed:
      - run-tests
    - get: git-dutyfree-new
      trigger: true
      passed:
      - run-elm-tests
    - get: every-day
      trigger: true
    - get: git-dutyfree-gh-pages
    - task: generate-html
      file: ci/generate-html.yml
      params:
        GITHUB_TOKEN: ((dutyfreeci.github_token))
    - task: commit
      file: ci/commit.yml
      params:
        SLACK_HOOK: ((dutyfreeci.slack_hook))
    - put: git-dutyfree-gh-pages
      params:
        repository: git-dutyfree-gh-pages-output

