resources:
- name: git-dutyfree
  type: git
  icon: store-24-hour
  source:
    uri: git@github.com:concourse/dutyfree.git
    branch: pipeline-testing
    private_key: ((duty-free-deployment-key))
- name: git-dutyfree-gh-pages
  type: git
  icon: shopping
  source:
    uri: git@github.com:concourse/dutyfree.git
    branch: gh-pages
    private_key: ((duty-free-deployment-key))

jobs:
- name: run-tests
  plan:
  - get: git-dutyfree
    trigger: true
  - task: run-tests
    file: git-dutyfree/ci/run-test/task.yml

- name: build
  plan:
    - get: git-dutyfree
      trigger: true
      passed: [run-tests]
    - get: git-dutyfree-gh-pages
    - task: generate-html
      file: git-dutyfree/ci/generate-html/task.yml
    - task: commit
      file: git-dutyfree/ci/commit/task.yml
    - put: git-dutyfree-gh-pages
      params:
        repository: git-dutyfree-gh-pages-output
