resources:
- name: git-dutyfree
  type: git
  icon: store-24-hour
  source:
    uri: git@github.com:concourse/dutyfree.git
    branch: master
    private_key: ((ci.private))
- name: git-dutyfree-gh-pages
  type: git
  icon: shopping
  source:
    uri: git@github.com:concourse/dutyfree.git
    branch: gh-pages
    private_key: ((ci.private))
- name: every-day
  type: time
  source:
    start: 8:00 AM
    stop: 9:00 AM

jobs:
- name: run-tests
  plan:
  - get: git-dutyfree
    trigger: true
  - task: run-tests
    file: git-dutyfree/ci/run-test/task.yml

- name: build
  plan:
    - get: git-dutyfree
      trigger: true
      passed: [run-tests]
    - get: every-day
      trigger: true
    - get: git-dutyfree-gh-pages
    - task: generate-html
      file: git-dutyfree/ci/generate-html/task.yml
      params:
        GITHUB_TOKEN: ((github_token))
    - task: commit
      file: git-dutyfree/ci/commit/task.yml
      params:
        SLACK_HOOK: ((slack-hook))
    - put: git-dutyfree-gh-pages
      params:
        repository: git-dutyfree-gh-pages-output
